version: 2
jobs:
  common:
    working_directory: /go/src/github.com/aizu-go-kapro/whroom
    docker:
      - image: ktr0731/circleci-evans

    steps:
      - checkout

      - run:
          name: build
          command: make build

  update-release:
    working_directory: /go/src/github.com/aizu-go-kapro/whroom
    docker:
      - image: ktr0731/circleci-evans

    steps:
      - checkout

      - run:
          name: install bump command
          command: go get github.com/ktr0731/go-semver/cmd/bump

      - run:
          name: update GitHub releases and update brew formula
          command: make brew-update

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - common
      - update-release:
          requires:
            - common
          filters:
            branches:
              only:
                - master
